name: Update badges

on:
  workflow_dispatch: # run manually
  schedule:
    # Runs at 1am UTC on Sunday
    - cron: "0 1 * * 0"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:

              - name: Badges - Readme
                uses: pemtajo/badge-readme@2.4.0
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: Ringwraith-org/Ringwraith-org
          CREDLY_SORT: RECENT
          CREDLY_USER: piers-margetts
